### ISSUE TITLE
Widgets overview

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess#136]
This is an overview of essentials to resolve for a first public version of the widgets:

### Selected

- [x] Implement scipp/ess#138.
- [x] Implement optional parameters. scipp/ess#131
- [x] Implement scipp/ess#140.
- [ ] scipp/ess#129
- [ ] Show outputs using a vertical layout of checkboxes (instead of list, avoids need to use shift or ctrl ubttons)?
- [ ] Show extended outputs as combo-box, so they are mostly hidden by default
- [ ] Fix some UI logic around enabling/disabling buttons, make sure things can be run again, ...
- [ ] Implement mappable widget wrapping arbitrary other widgets, where rows can be added/removed, yielding a tuple of parameter values. Probably add a `mappable` field to `class Parameter` to enable this.
- [ ] Low hanging fruit for look&feel: Type formatting, description display, ...
- [ ] Split out workflow&output selection to its own widget, make it displayable in a tab (param settings should be in second tab).
- [x] Helper functions to create widgets, instead of creating a single one in the module (some notebooks will need to create multiple workflow widgets). scipp/ess#133 
- [ ] Parameter that can take existing Python object as input. The widget should parse the global namespace (maybe similar to https://github.com/scipp/scipp/edit/main/src/scipp/object_list.py?), providing a drop-down list of objects to select from. May be filtered by type.
- [x] scipp/ess#108
- [x] Add tests

### Needs more thought

- [ ] How to select files on the server using a `FilenameWidget`? 
- [ ] Consider scipp/ess#135.

**Comment by YooSunYoung** [comment]
(moved to first post)
